[package]
name = "examples"
version = "0.2.0"
authors = ["Markus Mayer <widemeadows@gmail.com>"]
edition = "2018"
default-run = "gitversion"

[[bin]]
name = "gitversion"
path = "src/gitversion.rs"

[build-dependencies]
dotnet-gitversion-build = { path = "../gitversion-build" }
